# Site settings
title: Miracleyin's Blog
author: yinzhang
author_avatar: /images/header1.jpg
email: miracleyin@live.com
description: 一件事没法评估就没法优化
url: "https://miracleyin.github.io/"
domain: "https://miracleyin.github.io/"
github_username: Miracleyin
github_site_repo: MIracleyin/Miracleyin.github.io
disqus: monsterslayer


# Build settings
highlighter: rouge
markdown: kramdown
kramdown:
    syntax_highlighter: rouge
    extensions: ["fenced_code_blocks", "autolink", "tables", "smart"]

sass:
    style: :compressed
    sass_dir: _sass

permalink: pretty
excerpt_separator: "<!-- more -->"

# path
categories_path: categories/
tags_path: tags/


gems:
  - jekyll-sitemap
